package command;

public enum CommandType {
    CREATE_DOCTOR,
    CREATE_PATIENT,
    CREATE_ADMISSION,
    DELETE_PATIENT,
    UPDATE_PATIENT,
    UPDATE_ADMISSION,
    WRITE_ALL_PATIENTS,
    WRITE_ALL_DOCTORS,
    WRITE_ALL_ADMISSION,
    EXIT,
    UNDEFINED,
    SINGLETON;
}
